query getCharacters($page: Int!, $name: String) {
  characters(page: $page, filter: { name: $name }) {
    results {
      id
      name
      status
      species
      gender
      image
    }
    info {
      count
      pages
      next
      prev
    }
  }
}
